server:
  port: 4079

spring:
  application:
    name: leaderboard-service
  datasource:
    url: jdbc:postgresql://localhost:5432/leaderboard_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:4070/eureka/
  instance:
    prefer-ip-address: true
